apiVersion: v2
name: clickhouse
description: Clickhouse Cluster Configuration. This assumes a the affinity CH operator (https://docs.altinity.com/clickhouse-operator/ ) has already been installed.
version: 0.0.3
maintainers:
  - name: esnet
    email: "esnet-seg-ma@lbl.gov"
## This Chart may also be helpful: https://github.com/Altinity/helm-charts/tree/main/charts/clickhouse
